name: Daily Nogizaka Schedule

on:
  schedule:
    # 毎日 21:00 (日本時間) に実行
    # UTC（世界標準時）なので 9時間引いて 12:00 に設定
    - cron: "0 15 * * *"
  workflow_dispatch: # 手動で実行ボタンを押せるようにする

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas line-bot-sdk webdriver-manager google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python nogi_line.py
